### ISSUE TITLE
drbdtop doesn't show resources 

### ISSUE THREAD

**Issue by Osa1989** [LINBIT/drbdtop#16]
**Describe the bug**
when I start drbdtop it doesn't show me any resources

**To Reproduce**
Start dtrbdtop as root

**Expected behavior**
It should show me the resources

**Capture Raw Resource Data**
drbdsetup events2 --timestamps --statistics --now
received netlink error reply: Operation not supported

**Distro**
 - Ubuntu
 - Version 16.04

**Comment by rck** [comment]
`drbdtop` uses `drbdsetup` to gather information. Most likely the DRBD kernel module you use is too old and does not even support  "events2" and you get an `EOPNOTSUPP`.

You probably want to use a newer kernel module anyways, for DRBD8.4 this would then be version 8.4.11. Or you use DRBD9. Or you use an outdated intree module and stop using `drbdtop`, and use plain `drbdsetup status` instead.

Closing this, I'm pretty sure you just use outdated DRBD. But thanks, drbdtop could be a bit more helpful when it detects such a situation.

**Comment by Osa1989** [comment]
Can you add this to the README please
I wasted some time troubleshooting this.

**Comment by haySwim** [comment]
There is error reporting that the TUI view doesn't display, but could.

Even so, we probably need to die if the utils are not an appropriate version. @rck can you think of a way the version checking [here](https://github.com/LINBIT/drbdtop/blob/master/pkg/display/utils.go#L29) could fail, but the utils still be able to provide the correct info?

**Comment by rck** [comment]
I'm against adding it to the README, that does not solve it.

@haySwim I had the same idea, dying if the versions don't match is the way to go. One thing I can think of is that I introduced `DRBD_KERNEL_VERSION ` only for drbd9-utils and that somewhere in March 2017. But the fallback code should cover that. Anyways, what I would like to do:

- use some proper function definition(s), one that return an error
- use `DRBD_KERNEL_VERSION_CODE`, which should be there for a very long time. 9 and 8.
- expose that via a proper struct that has 'major', 'minor', 'patch' (or however semver exactly calls them).
- split this "does everything function" into multiple functions. Maybe keep a "does everything" that generates the final string, but calls the the dedicated ones. Then at startup we can call the dedicated function for the kernel and/or utils and check some 'blacklist' or some 'is older than'.

Feel free to work on it, otherwise it is on my table.

I reopen this for tracking.

**Comment by haySwim** [comment]
Yeah, like the idea of keeping the "does everything function" but having it just called the dedicated ones.

One of my original ideas was for collectors to send an EOF event when they were done, and to have some upper layer decide what to do with this info. The TUI has a nop branch for that right now https://github.com/LINBIT/drbdtop/blob/master/pkg/display/fancy_tui.go#L122 

Maybe that should be changed from a EOF to something like FATAL and it passes up some info about why the collector had to terminate. Does that sound reasonable @rck

**Comment by rck** [comment]
@haySwim Sounds like a good idea. I'd say there is room for both. A static check at at startup and collectors reporting when something is wrong. Like an unrecoverable state.

I pushed my ideas for the static check (and version gathering refactoring) to the develop branch. Review/ACKs welcome.
