### ISSUE TITLE
defect terminal fonts used

### ISSUE THREAD

**Issue by jojoax** [LINBIT/drbdtop#6]
After building and testing @ my test cluster the useabiliity is broken due visual defective screen views:

![go_20180710_100815](https://user-images.githubusercontent.com/4421146/42497313-404a764e-8429-11e8-9441-a240c9e8358b.png)

System Arch Linux Rolling Release, Status from 2018-07-10 10:00h.
Used via ssh remote terminal, KDE/konsole as xterminal.

**Comment by haySwim** [comment]
What kind of fonts packages are installed on your system? It's been a while since I used Arch, but they're pretty sparse by default right? Maybe there's some unicode-related package you need to install in your system.

**Comment by jojoax** [comment]
Standard, minimal on Console.
Font by it self has to be irrelevant for such system near tool. Special Chars shold never used in Termial environments of productive sorroundings. If did so, =>> Resul see Screen Shot, unusable.

**Comment by raltnoeder** [comment]
Cannot reproduce, neither with any of the fonts I have installed nor with the locale. It could also be the setting of the `TERM` variable. If that does not match what the terminal emulator implements, then the output will be messed up (e.g., if I run with `vt100` in a KDE Konsole, then I get incorrect output).

Unfortunately, terminal types, terminal control and terminal IO on any kind of Unix-like operating system is a total train wreck, due to the presence of half a million different terminal types that are all incompatible with each other, a lack of sane standards and the failure of the multitude of different terminal emulators to fully and correctly implement the feature set of the terminal types they claim to implement.

Anyhow, the utility has certain requirements, which includes a font that is able to render box drawing characters and a terminal that implements certain ANSI escape sequences.

**Comment by nicholas-cross-fujitsu** [comment]
I know this is closed but i have this same issue in a PuTTY session to CentOS8 streams.#

![image](https://user-images.githubusercontent.com/64132351/106202808-58fd4b80-61b2-11eb-9f3e-b05b8bae1d8c.png)

**Comment by veitw** [comment]
I have encountered this issue on CentOS 8, too, connecting via SSH from GNOME Terminal with `LANG="de_DE.UTF-8"` and `TERM="xterm-256color"`.

This does not occur with `TERM="xterm"`, so as a workaround I set up an alias in `~/.bashrc`:
```
alias drbdtop="TERM=xterm drbdtop"
```

HtH
// Veit
